### ISSUE TITLE
Using the Swift .xctemplate will fail with multiple classes

### ISSUE THREAD

**Issue by DerekSelander** [kattrali/Xcode-Plugin-Template#31]
Once you create a new class other than the default class included in the xctemplate, the plugin will not load. 

ex: 
Add class `class SomeClass {`} at the top of the .swift file included in the template. 
Potentially a Swift module issue or an omitted parameter in the xctemplate?

**Comment by kattrali** [comment]
Very odd. o_0;; Does this also occur with multiple files, or just multiple classes in a single file?

**Comment by DerekSelander** [comment]
It occurs for both cases. Once another class is compiled in, the plugin fails to load. I'll keep an eye on any notable diffs between the build settings, plist, and xctemplates used for other projects to see if something is missing.
 
Definitely a weird one.

**Comment by creinders** [comment]
Hi,

I was struggling with exactly the same problem and I noticed that turning the "Embedded Content Contains Swift Code" option to YES under Build Settings of the target solved it. Here my answer on stackoverflow http://stackoverflow.com/a/29872089/1442208

Hopefully that also works for you!
