### ISSUE TITLE
run a new Xcode app?

### ISSUE THREAD

**Issue by huaxi** [kattrali/Xcode-Plugin-Template#40]
when I run this template,why it creates a new Xcode application?

**Comment by kattrali** [comment]
Hi @huaxi, 

this template is intended to assist in developing Xcode plugins. By default it is configured to build your code as a plugin bundle and launch a new instance of Xcode, similar to developing any other Mac app. You can add breakpoints and debug the new Xcode instance launched by using the run action.

**Comment by huaxi** [comment]
got it,thanks, Xcode debug Xcode ,this is a good idea .😃
